[tool.commitizen]
name = "cz_customize"
tag_format = "$version"
version_scheme = "semver"
version = "7.3.7"
update_changelog_on_bump = true
changelog_incremental = true
version_files = [
	"VERSION",
	"package.json:version"
]
pre_bump_hooks = "npx task build"
[tool.commitizen.customize]
message_template = "{{change_type}}:{% if show_message %} {{message}}{% endif %}"
commit_parser = '^((?P<change_type>feat|fix|refactor|perf|style|test|ci|build|doc|docs|chore|BREAKING CHANGE)(?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?|\w+!):\s(?P<message>.*)?'
change_type_order = ["BREAKING CHANGE", "Feat", "Fix", "refactor", "perf", "test", "style", "doc", "docs", "CI", "Build", "Chore"]
change_type_map = {"feat"= "Feat","fix"= "Fix","refactor"= "Refactor","perf"= "Perf","chore"= "Chore", "ci" = "CI", "build" = "Build", "style" = "Style", "doc" = "Docs", "docs" = "Docs", "test" = "Test"}